name: Upload Python Package
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-python-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: python3 -m pip install --upgrade build && python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        verbose: true
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
